### ISSUE TITLE
根据您的代码做了一些优化。

### ISSUE THREAD

**Issue by nostarsnow** [ZZES-ZCDC/zzes-mock#2]
感谢提供的代码。
添加了参数required的配置和验证。类swagger 
增加了预览restc时直接填写好参数名的功能。类swagger 
不知道您是否需要。我提交个pr？
为什么我提交个pr也这么纠结呢。
因为我从来没有提交过呀。

**Comment by klren0312** [comment]
# 可以啊, 感谢
